# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-20 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theremodels',
            name='png_file',
            field=models.FileField(default='', upload_to='media/mtl/%Y%m%d', verbose_name='\u6a21\u578b\u56fe\u7247'),
        ),
        migrations.AlterField(
            model_name='theremodels',
            name='there_file',
            field=models.FileField(default='', upload_to='media/mtl/%Y%m%d'),
        ),
    ]
